apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: 'slack'
      routes:
        - match:
            severity: page
          receiver: 'slack'
    receivers:
      - name: 'slack'
        webhook_configs:
          - url: 'http://example.com/alert' # replace with real endpoint in production
