apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager:9093']

    rule_files:
      - "/etc/prometheus/rules/*.rules"

    scrape_configs:
      - job_name: 'app'
        static_configs:
          - targets: ['app:8080']

      - job_name: 'cadvisor'
        static_configs:
          - targets: ['cadvisor:8080']

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  app-down.rules: |
    groups:
      - name: app.rules
        rules:
          - alert: AppDown
            expr: up{job="app"} == 0
            for: 30s
            labels:
              severity: page
            annotations:
              summary: "App target is down"
              description: "Prometheus job 'app' has no healthy instances for more than 30s."
