version: "3.8"

services:
  localstack:
    image: localstack/localstack:2.3
    container_name: sre-lab-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=iam,ec2,s3,ecr,sts,cloudwatch,logs
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_PERSISTENCE=1
      - LS_DISABLE_SSL=1
    volumes:
      - ./data:/var/lib/localstack
