apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sre-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/SantiagoSalazarPavajeau/sre-lab'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sre-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
